version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club

    tables:
      - name: customers
        description: "Model based upon our customers"
        columns:
          - name: id
            description: "Primary key of the model"
            tests:
              - unique
              - not_null
              - relationships:
                  to: source('coffee_shop','customers')
                  field: id
                  
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - relationships:
                  to: source('coffee_shop', 'customers')
                  field: id